name: Package PaddleOCR Tiny Models

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create PaddleOCR model archives
        run: |
          tar -cf ocr/ppocrv6-tiny-det.tar -C ocr/det .
          tar -cf ocr/ppocrv6-tiny-rec.tar -C ocr/rec .

      - name: Commit model archives
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add ocr/ppocrv6-tiny-det.tar
          git add ocr/ppocrv6-tiny-rec.tar

          git diff --cached --quiet || \
            git commit -m "Package PP-OCRv6 Tiny models"

          git push
